#!/usr/bin/env perl

use strict;
use warnings;

use Math::Trig;

use constant CIRCLE => 16384;

print "/* sin.c - autogenerated */\n\n", "#include <stdint.h>\n\n",
 "int32_t itrig_sin_table[] = {\n";

my @buf = ();
for my $a ( 0 .. CIRCLE / 4 ) {
  push @buf, sprintf '0x%08x',
   int( sin( $a * 2 * pi / CIRCLE ) * 0x7fffffff );
  if ( @buf > 4 ) {
    print '  ', join( ', ', @buf, '' ), "\n";
    @buf = ();
  }
}
print '  ', join( ', ', @buf ), "\n";
print "};\n";

# vim:ts=2:sw=2:sts=2:et:ft=perl

